name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool: myAgent
    steps:
    - task: CmdLine@2
      displayName: Install NewMan
      continueOnError: true
      inputs:
        script: sudo npm install -g newman
        workingDirectory: 'starter-code/automatedtesting/postman'
    - task: CmdLine@2
      displayName: DISPLAY NAME
      inputs:
        script: newman run StarterAPIs.json
        workingDirectory: DEFAULT WORKING DIRECTORY
    